### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Pusherman2** [Naseefabu/HFTBOT#1]
Hi there,

Interesting project. I am however, having some issues when compiling:

`[  8%] Building CXX object CMakeFiles/hftbot.dir/core/features.cpp.o
In file included from /Documents/HFTBOT/core/features.hpp:5,
                 from /Documents/HFTBOT/core/features.cpp:1:
/Documents/HFTBOT/exchanges/utils.hpp:8:10: fatal error: boost/url.hpp: No such file or directory
    8 | #include <boost/url.hpp>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
`
Maybe related to one of your questions?
https://stackoverflow.com/questions/72139531/why-do-i-getting-boost-url-linking-error

And is there anything else that requires to be configured such as API keys etc?

Kind regards.

P.S: Discord link is expired.

**Comment by berdvana** [comment]
did you cloned the repo with --recurse-submodules ? maybe boost URL library isn't initialized.
Discord link is updated now.

**Comment by Pusherman2** [comment]
This fixed the issue, thank you. Issue can be closed.
